version: '3.8'
services:
  # flask-app:
  #   container_name: flask-backend
  #   # image: konstantinosrazgkelisonelity/flask_backend:latest
  #   # pull_policy: always

  #   build:
  #     context: ./containers/flask-container
  #     dockerfile: Dockerfile.local
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./containers/flask-container/app:/app  # Mount the app source code
  #   environment:
  #     - FLASK_ENV=development  # Set Flask to development mode to enable auto-reload
  #     - FLASK_DEBUG=True
  #     - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/
  #     - SPARK_HOST=local
  #   networks:
  #     - front-back-network
  #   command: ["python3", "app.py"]

  # front:
  #   container_name: ts_frontend
  #   # image: konstantinosrazgkelisonelity/ts_frontend:latest
  #   build:
  #     context: ./containers/front
  #     dockerfile: Dockerfile.local
  #   pull_policy: always
  #   restart: always
  #   ports:
  #     - "80:80" 
  #   env_file:
  #     - ./containers/front/app/.env.local
  #   networks:
  #     - front-back-network
  #   # command: ["sleep", "infinity"]

  backend:
    container_name: django-backend
    build:
      context: ./containers/django-container  # Adjust this to the path of your Django project
      dockerfile: Dockerfile.local  # Ensure you have a Dockerfile.local for Django
    restart: always
    ports:
      - "8000:8000"  # Expose port 8000 for Django
    volumes:
      - ./containers/django-container/app:/app  # Mount the app source code
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings  # Adjust with your settings module
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydb  # Adjust as necessary
      - SPARK_HOST=local
      - DEBUG=True
    networks:
      - front-back-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13  # Use the PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: mydb  # Database name
      POSTGRES_USER: myuser  # Username
      POSTGRES_PASSWORD: mypassword  # Password
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    networks:
      - front-back-network

networks:
  front-back-network:
    driver: bridge
  