# Generated by Django 3.2.25 on 2024-10-24 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import documents_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=documents_app.models.Document.get_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users_app.user')),
            ],
        ),
    ]
