# Generated by Django 3.2.25 on 2024-10-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0005_alter_sparkjob_accessible_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkjob',
            name='title',
            field=models.CharField(default='Spark Job', max_length=255),
        ),
    ]
