apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  labels:
    app: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: konstantinosrazgkelisonelity/flask_backend
          imagePullPolicy: Always
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DATABASE_URL
              value: postgres://root:example@postgres:5432/mydatabase
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  labels:
    app: flask-backend
spec:
  selector:
    app: flask-backend
  ports:
    - port: 8080
      targetPort: 8080
