apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
spec:
  serviceName: spark-worker-headless  # Name of the headless service
  replicas: 5  # Number of worker replicas
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest
        ports:
        - containerPort: 8081  # Spark worker web UI port
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"  # Connect to Spark master
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-headless
spec:
  clusterIP: None  # This makes it a headless service for stable DNS
  ports:
  - port: 8081  # Spark Worker web UI port
    targetPort: 8081
  selector:
    app: spark-worker
