apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-cluster-pv
spec:
  capacity:
    storage: 3Gi  # Size of the volume
  accessModes:
    - ReadWriteMany  # Access mode
  hostPath:
    path: /mnt/app/app/backend/static  # Path on the host