apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-cluster-pv
spec:
  capacity:
    storage: 3Gi  # Size of the volume
  accessModes:
    - ReadWriteMany  # Access mode
  hostPath:
    path: /app/app/backend/media  # Path on the host